# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: gto-test
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express    
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort : 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key : mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD   
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key : mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER   
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key : database_url

              

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: gto-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    nodePort : 30000
  selector:
    app: mongo-express
  type: LoadBalancer